"""Static inventory: no imports from application modules."""
import ast,json,hashlib
from pathlib import Path
OUT=Path(__file__).resolve().parent;ROOT=OUT.parents[2]
p=ROOT/'apps/bot/app/main.py';tree=ast.parse(p.read_text());route=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='route_message')
rows=[]
for n in route.body:
 if not isinstance(n,ast.If):continue
 commands=[v.value for v in ast.walk(n.test) if isinstance(v,ast.Constant) and isinstance(v.value,str) and v.value.startswith('/')]
 if not commands:continue
 calls=sorted({x.func.id for st in n.body for x in ast.walk(st) if isinstance(x,ast.Call) and isinstance(x.func,ast.Name)})
 rows.append({'commands':commands,'line':n.lineno,'calls':calls,'ai_job':'create_ai_job' in calls,'possible_mutations':[c for c in calls if c.startswith(('save_','update_','mark_','discard_','create_','handle_strength'))]})
(OUT/'ejecuciones/inventario.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
lines=['# Inventario del flujo actual','','Generado a partir del AST de `apps/bot/app/main.py`; la columna de escritura indica llamadas potenciales, no efectos de todas las variantes.','','| Entrada | Línea | Destino | IA | Posibles escrituras |','| --- | --- | --- | --- | --- |']
for r in rows:
 lines.append('| '+' / '.join(r['commands'])+' | '+str(r['line'])+' | '+', '.join(r['calls'])+' | '+('Sí' if r['ai_job'] else 'No')+' | '+(', '.join(r['possible_mutations']) or 'Ninguna directa')+' |')
lines += ['','Texto libre: crea trabajo IA. Voz: el webhook crea trabajo con audio_file_id; la transcripción se realiza en el Mac. Adjuntos PDF/DOCX: trabajo de prueba deportiva, no consulta deportiva ordinaria.','','## Generadores y contratos','','| Elemento | Quién lo llama | Responsabilidad / solapamiento | Estado |','| --- | --- | --- | --- |','| `sync.recommend_next_workout` | `build_payload` | Sugerencia calculada a partir de carga/calendario; otro origen de recomendación | Se publica en snapshot |','| `coach.format_feedback`, `format_next`, `format_week`, `format_adjust` | Enrutador / `build_ai_brief` según función | Valoraciones y recomendaciones deterministas que conviven con Ollama | Depende de la función |','| `coach.build_week_plan` | `/plan`, `/plan_semana` | Genera plan; el enrutador lo guarda incluso al consultar | Escribe vía `save_training_plan` |','| `ai_worker.compact_context` | `call_ollama` | Reduce actividades, historial, bienestar y plan antes de validar | Sin persistencia propia |','| `coach_generation_context.build_snapshot` | `generate_validated` | Filtra hechos, fechas, fuentes y permisos | Instantánea inmutable |','| `coach_generation_pipeline` | `ai_worker.call_ollama` | Modelo + reparación acotada | Sin I/O salvo callback |','| `coach_generation_resolver` / `renderer` | Pipeline | Resuelve decisiones y produce frases canónicas | Sin persistencia |','| `ai_worker._validate_ollama_response` | Ruta antigua / pruebas | Valida contrato con answer; no es el pipeline que usa call_ollama hoy | Duplicación de rutas a revisar |','| `app.ai_contracts` / `garmin_sync.ai_contracts` | Bot / worker | Dos copias del contrato público | Hashes en referencia.json |','| `coach_generation_contracts` | Pipeline | Contrato interno distinto, sin answer libre | No debe confundirse con duplicación accidental |','| `store` / repositorios de propuestas | API y enrutador | Ficheros o PostgreSQL; permisos y revisiones | Persistencia |','','## Contradicciones con documentación','','- README: afirma un único flujo para comandos deportivos; E14 demuestra que `/feedback` no crea trabajo IA. Las pruebas existentes incluso exigen respuestas directas para estos comandos.','- README: describe explicación en prosa de Ollama; el pipeline vigente prohíbe `answer` y el renderer compone el texto.','- `docs/coach-validation.md`: indica implementación pendiente de integración; el checkout main auditado contiene el pipeline. No se ha atestiguado el commit activo de Railway.','','## Lecturas con efectos potenciales','','- `GET /ai/jobs/next` reclama un trabajo y prepara permisos: no usar para inspección.','- `GET /status` y `/history` llaman loaders PostgreSQL que ejecutan `ensure_schema`. La función sale tras un SELECT cuando detecta la migración; en otros estados puede ejecutar DDL. Sin conocer el esquema remoto no se ha llamado a estas rutas.']
(OUT/'inventario.md').write_text('\n'.join(lines)+'\n')
print(len(rows),'ramas de comandos inventariadas')
